### ISSUE TITLE
Post.title field missing on client after sync

### ISSUE THREAD

**Issue by chuckatc** [sebsto/amplify-datastore-js-e2e#1]
@sebsto , thanks for the talk, blog and repo!

Unfortunately seeing an issue where the title field is visible for a split-second after clicking "NEW", then it disappears from the row in the table:
<img width="494" alt="Screen Shot 2019-12-09 at 5 47 23 pm" src="https://user-images.githubusercontent.com/18747662/70417163-c5038880-1ab4-11ea-9d03-0dceb288f3b0.png">

When offline, the new title is visible until going online:
<img width="747" alt="Screen Shot 2019-12-09 at 6 13 53 pm" src="https://user-images.githubusercontent.com/18747662/70417386-3ba08600-1ab5-11ea-93ca-ec4a0a7363b6.png">

The title field is present and populated in DynamoDB but absent from where I'm guessing it should be in IndexedDB:
<img width="184" alt="Screen Shot 2019-12-09 at 6 06 58 pm" src="https://user-images.githubusercontent.com/18747662/70417717-f29d0180-1ab5-11ea-8030-77806dfa9fce.png">
<img width="922" alt="Screen Shot 2019-12-09 at 5 48 50 pm" src="https://user-images.githubusercontent.com/18747662/70417739-fc266980-1ab5-11ea-9f3b-142deb0eeb08.png">

Looking at the console output from App.js, title is present in the first operation but not the subsequent ones (or is that expected?)
<img width="778" alt="Screen Shot 2019-12-09 at 6 04 32 pm" src="https://user-images.githubusercontent.com/18747662/70418303-49efa180-1ab7-11ea-8a5a-f4b5715f2360.png">

Note that I've tried deleting and recreating this (twice) following README.md, giving the same behaviour. Also tried emptying both DynamoDB tables, deleting the IndexedDB, and doing npm start again, with the same result.

Any more info I can gather?

Versions:
- node v12.13.1
- amplify 4.5.0
- Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- package.json has:
```json
    "dependencies": {
        "@aws-amplify/core": "^2.2.0",
        "@aws-amplify/datastore": "^1.0.2",
        "@testing-library/jest-dom": "^4.2.4",
        "@testing-library/react": "^9.3.2",
        "@testing-library/user-event": "^7.1.2",
        "react": "^16.12.0",
        "react-dom": "^16.12.0",
        "react-scripts": "3.3.0"
    },
```

**Comment by sebsto** [comment]
Sorry to hear you're experiencing issue with this demo.  I think the problem is related to https://github.com/aws-amplify/amplify-cli/issues/2945#event-2863997461

Can you give it a try and report back ?

**Comment by sebsto** [comment]
I just tested again with the change suggested in the issue referenced above and it is working correctly.

As of today, it is required to manually change `string` to `String` (uppercase S) in `models/schema.js`, until the fix will land into production.

**Comment by chuckatc** [comment]
@sebsto, confirming the demo works as expected with the workaround. Thanks for the rapid reply.

**Comment by sebsto** [comment]
The fix is in the `npm` repository. A ˋnpm update ˋ should correct the issue.

**Comment by chuckatc** [comment]
@sebsto , thanks for the follow-up. Confirming schema.js is now generated as expected.
